/* Generated By:JJTree: Do not edit this line. C:/cygwin/home/Kabir/sourcecontrol/jboss-aop/aop/src/main/org/jboss/aop/pointcut/ast\PointcutExpressionParserVisitor.java */

package org.jboss.aop.pointcut.ast;

public interface PointcutExpressionParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTExecutionOnly node, Object data);
  public Object visit(ASTBoolean node, Object data);
  public Object visit(ASTComposite node, Object data);
  public Object visit(ASTNot node, Object data);
  public Object visit(ASTSub node, Object data);
  public Object visit(ASTAnd node, Object data);
  public Object visit(ASTOr node, Object data);
  public Object visit(ASTCFlowExpression node, Object data);
  public Object visit(ASTCFlowBoolean node, Object data);
  public Object visit(ASTNotCFlow node, Object data);
  public Object visit(ASTCompositeCFlow node, Object data);
  public Object visit(ASTSubCFlow node, Object data);
  public Object visit(ASTAndCFlow node, Object data);
  public Object visit(ASTOrCFlow node, Object data);
  public Object visit(ASTPointcut node, Object data);
  public Object visit(ASTCFlow node, Object data);
  public Object visit(ASTAll node, Object data);
  public Object visit(ASTCall node, Object data);
  public Object visit(ASTWithin node, Object data);
  public Object visit(ASTWithincode node, Object data);
  public Object visit(ASTExecution node, Object data);
  public Object visit(ASTConstruction node, Object data);
  public Object visit(ASTHas node, Object data);
  public Object visit(ASTHasField node, Object data);
  public Object visit(ASTGet node, Object data);
  public Object visit(ASTSet node, Object data);
  public Object visit(ASTFieldExecution node, Object data);
  public Object visit(ASTMethod node, Object data);
  public Object visit(ASTException node, Object data);
  public Object visit(ASTAttribute node, Object data);
  public Object visit(ASTConstructor node, Object data);
  public Object visit(ASTParameter node, Object data);
  public Object visit(ASTAllParameter node, Object data);
  public Object visit(ASTField node, Object data);
}
