/* Generated By:JJTree: Do not edit this line. C:/cygwin/home/Kabir/sourcecontrol/jboss-aop/aop/src/main/org/jboss/aop/pointcut/ast\PointcutExpressionParserTreeConstants.java */

package org.jboss.aop.pointcut.ast;

public interface PointcutExpressionParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTEXECUTIONONLY = 1;
  public int JJTVOID = 2;
  public int JJTBOOLEAN = 3;
  public int JJTCOMPOSITE = 4;
  public int JJTNOT = 5;
  public int JJTSUB = 6;
  public int JJTAND = 7;
  public int JJTOR = 8;
  public int JJTCFLOWEXPRESSION = 9;
  public int JJTCFLOWBOOLEAN = 10;
  public int JJTNOTCFLOW = 11;
  public int JJTCOMPOSITECFLOW = 12;
  public int JJTSUBCFLOW = 13;
  public int JJTANDCFLOW = 14;
  public int JJTORCFLOW = 15;
  public int JJTPOINTCUT = 16;
  public int JJTCFLOW = 17;
  public int JJTALL = 18;
  public int JJTCALL = 19;
  public int JJTWITHIN = 20;
  public int JJTWITHINCODE = 21;
  public int JJTEXECUTION = 22;
  public int JJTCONSTRUCTION = 23;
  public int JJTHAS = 24;
  public int JJTHASFIELD = 25;
  public int JJTGET = 26;
  public int JJTSET = 27;
  public int JJTFIELDEXECUTION = 28;
  public int JJTMETHOD = 29;
  public int JJTEXCEPTION = 30;
  public int JJTATTRIBUTE = 31;
  public int JJTCONSTRUCTOR = 32;
  public int JJTPARAMETER = 33;
  public int JJTALLPARAMETER = 34;
  public int JJTFIELD = 35;


  public String[] jjtNodeName = {
    "Start",
    "ExecutionOnly",
    "void",
    "Boolean",
    "Composite",
    "Not",
    "Sub",
    "And",
    "Or",
    "CFlowExpression",
    "CFlowBoolean",
    "NotCFlow",
    "CompositeCFlow",
    "SubCFlow",
    "AndCFlow",
    "OrCFlow",
    "Pointcut",
    "CFlow",
    "All",
    "Call",
    "Within",
    "Withincode",
    "Execution",
    "Construction",
    "Has",
    "HasField",
    "Get",
    "Set",
    "FieldExecution",
    "Method",
    "Exception",
    "Attribute",
    "Constructor",
    "Parameter",
    "AllParameter",
    "Field",
  };
}
