/* Generated By:JJTree: Do not edit this line. C:/cygwin/home/Kabir/sourcecontrol/jboss-aop/aop/src/main/org/jboss/aop/pointcut/ast\TypeExpressionParserVisitor.java */

package org.jboss.aop.pointcut.ast;

public interface TypeExpressionParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTBoolean node, Object data);
  public Object visit(ASTComposite node, Object data);
  public Object visit(ASTNot node, Object data);
  public Object visit(ASTSub node, Object data);
  public Object visit(ASTAnd node, Object data);
  public Object visit(ASTOr node, Object data);
  public Object visit(ASTHas node, Object data);
  public Object visit(ASTHasField node, Object data);
  public Object visit(ASTMethod node, Object data);
  public Object visit(ASTAttribute node, Object data);
  public Object visit(ASTConstructor node, Object data);
  public Object visit(ASTParameter node, Object data);
  public Object visit(ASTAllParameter node, Object data);
  public Object visit(ASTField node, Object data);
  public Object visit(ASTClass node, Object data);
  public Object visit(ASTException node, Object data);
}
