/* Generated By:JJTree: Do not edit this line. C:/cygwin/home/Kabir/sourcecontrol/jboss-aop/aop/src/main/org/jboss/aop/pointcut/ast\TypeExpressionParserTreeConstants.java */

package org.jboss.aop.pointcut.ast;

public interface TypeExpressionParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTBOOLEAN = 2;
  public int JJTCOMPOSITE = 3;
  public int JJTNOT = 4;
  public int JJTSUB = 5;
  public int JJTAND = 6;
  public int JJTOR = 7;
  public int JJTHAS = 8;
  public int JJTHASFIELD = 9;
  public int JJTMETHOD = 10;
  public int JJTATTRIBUTE = 11;
  public int JJTCONSTRUCTOR = 12;
  public int JJTPARAMETER = 13;
  public int JJTALLPARAMETER = 14;
  public int JJTFIELD = 15;
  public int JJTCLASS = 16;
  public int JJTEXCEPTION = 17;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Boolean",
    "Composite",
    "Not",
    "Sub",
    "And",
    "Or",
    "Has",
    "HasField",
    "Method",
    "Attribute",
    "Constructor",
    "Parameter",
    "AllParameter",
    "Field",
    "Class",
    "Exception",
  };
}
