

CREATE TABLE IF NOT EXISTS `cmpe281`.`LP_TASK` (
  `ID` INT NOT NULL,
  `DESC` VARCHAR(45) NULL,
  `OWNER` VARCHAR(45) NULL,
  `PLAN_START` DATETIME NULL,
  `PLAN_FINISH` DATETIME NULL,
  `DONE` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cmpe281`.`TENANT_TABLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cmpe281`.`TENANT_TABLE` (
  `TENANT_ID` VARCHAR(10) NOT NULL,
  `TABLE_NAME` VARCHAR(45) NOT NULL,
  `TABLE_DESC` VARCHAR(80) NULL,
  PRIMARY KEY (`TENANT_ID`, `TABLE_NAME`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cmpe281`.`TENANT_FIELDS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cmpe281`.`TENANT_FIELDS` (
  `TENANT_ID` VARCHAR(10) NOT NULL,
  `TABLE_NAME` VARCHAR(45) NOT NULL,
  `FIELD_NAME` VARCHAR(45) NOT NULL,
  `FIELD_TYPE` VARCHAR(80) NULL,
  `FIELD_COLUMN` INT NOT NULL,
  PRIMARY KEY (`TENANT_ID`, `TABLE_NAME`, `FIELD_NAME`),
  CONSTRAINT `fk_TENANT_FIELDS_TENANT_TABLE`
    FOREIGN KEY (`TENANT_ID` , `TABLE_NAME`)
    REFERENCES `cmpe281`.`TENANT_TABLE` (`TENANT_ID` , `TABLE_NAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cmpe281`.`TENANT_DATA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cmpe281`.`TENANT_DATA` (
  `RECORD_ID` VARCHAR(45) NOT NULL,
  `TENANT_ID` VARCHAR(10) NOT NULL,
  `TENANT_TABLE` VARCHAR(45) NULL,
  `COLUMN_1` VARCHAR(80) NULL,
  `COLUMN_2` VARCHAR(80) NULL,
  `COLUMN_3` VARCHAR(80) NULL,
  `COLUMN_4` VARCHAR(80) NULL,
  `COLUMN_5` VARCHAR(80) NULL,
  `COLUMN_6` VARCHAR(80) NULL,
  `COLUMN_7` VARCHAR(80) NULL,
  `COLUMN_8` VARCHAR(80) NULL,
  `COLUMN_9` VARCHAR(80) NULL,
  `COLUMN_10` VARCHAR(80) NULL,
  PRIMARY KEY (`TENANT_ID`, `RECORD_ID`))
ENGINE = InnoDB;


-- TENANT TABLE
insert into TENANT_TABLE( TENANT_ID, TABLE_NAME, TABLE_DESC )
values ( 'TA', 'LP_TASK', 'Task Table for LiquidPlanner' ) ;

-- TENANT FIELDS
insert into TENANT_FIELDS( TENANT_ID, TABLE_NAME, FIELD_NAME, FIELD_TYPE, FIELD_COLUMN ) values ( 'TA', 'LP_TASK', 'ID', 'INT', 1 ) ;
insert into TENANT_FIELDS( TENANT_ID, TABLE_NAME, FIELD_NAME, FIELD_TYPE, FIELD_COLUMN ) values ( 'TA', 'LP_TASK', 'DESC', 'VARCHAR(45)', 2 ) ;
insert into TENANT_FIELDS( TENANT_ID, TABLE_NAME, FIELD_NAME, FIELD_TYPE, FIELD_COLUMN ) values ( 'TA', 'LP_TASK', 'OWNER', 'VARCHAR(45)', 3 ) ;
insert into TENANT_FIELDS( TENANT_ID, TABLE_NAME, FIELD_NAME, FIELD_TYPE, FIELD_COLUMN ) values ( 'TA', 'LP_TASK', 'PLAN_START', 'DATETIME', 4 ) ;
insert into TENANT_FIELDS( TENANT_ID, TABLE_NAME, FIELD_NAME, FIELD_TYPE, FIELD_COLUMN ) values ( 'TA', 'LP_TASK', 'PLAN_FINISH', 'DATETIME', 5 ) ;
insert into TENANT_FIELDS( TENANT_ID, TABLE_NAME, FIELD_NAME, FIELD_TYPE, FIELD_COLUMN ) values ( 'TA', 'LP_TASK', 'DONE', 'VARCHAR(45)', 6 ) ;

-- QUERY
select T.TABLE_NAME, F.FIELD_NAME, F.FIELD_TYPE, F.FIELD_COLUMN
from TENANT_TABLE T, TENANT_FIELDS F
where T.TENANT_ID = F.TENANT_ID
and T.TENANT_ID = 'TA'
order by F.FIELD_COLUMN


-- TENANT_DATA Record Example
insert into TENANT_DATA (RECORD_ID, TENANT_ID, TENANT_TABLE, COLUMN_1, COLUMN_2, COLUMN_3, COLUMN_4, COLUMN_5, COLUMN_6  ) 
values ( '1001', 'TA', 'LP_TASK', '1001', 'Design Data Models', 'Paul', '2014-09-01', '2014-10-01', 'FALSE' ) ;

-- Test Queries
select * from LP_TASK ;
select * from TENANT_DATA where TENANT_ID = 'TA' ;


-- Column Header Query
select  T.TABLE_NAME, 
        C1.FIELD_NAME, C2.FIELD_NAME, C3.FIELD_NAME,
        C4.FIELD_NAME, C5.FIELD_NAME, C6.FIELD_NAME
from 	TENANT_TABLE T,
		TENANT_FIELDS C1,
		TENANT_FIELDS C2,
		TENANT_FIELDS C3,
		TENANT_FIELDS C4,
		TENANT_FIELDS C5,
		TENANT_FIELDS C6
where 	T.TENANT_ID = 'TA' 
and	   	T.TABLE_NAME = C1.TABLE_NAME and T.TENANT_ID = C1.TENANT_ID and C1.FIELD_COLUMN = 1
and	   	T.TABLE_NAME = C2.TABLE_NAME and T.TENANT_ID = C2.TENANT_ID and C2.FIELD_COLUMN = 2
and	   	T.TABLE_NAME = C3.TABLE_NAME and T.TENANT_ID = C3.TENANT_ID and C3.FIELD_COLUMN = 3
and	   	T.TABLE_NAME = C4.TABLE_NAME and T.TENANT_ID = C4.TENANT_ID and C4.FIELD_COLUMN = 4
and	   	T.TABLE_NAME = C5.TABLE_NAME and T.TENANT_ID = C5.TENANT_ID and C5.FIELD_COLUMN = 5
and	   	T.TABLE_NAME = C6.TABLE_NAME and T.TENANT_ID = C6.TENANT_ID and C6.FIELD_COLUMN = 6
UNION
select TENANT_TABLE, COLUMN_1, COLUMN_2, COLUMN_3, COLUMN_4, COLUMN_5, COLUMN_6 
from   TENANT_DATA
where  TENANT_ID = 'TA'	


-- -----------------------------------------------------
-- Table `cmpe281`.`TENANT_RECORDS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cmpe281`.`TENANT_RECORDS` (
  `RECORD_ID` VARCHAR(45) NOT NULL,
  `TENANT_ID` VARCHAR(10) NOT NULL,
  `TENANT_TABLE` VARCHAR(45) NULL,
  PRIMARY KEY (`RECORD_ID`, `TENANT_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cmpe281`.`TENANT_RECORD_EXTENSION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cmpe281`.`TENANT_RECORD_EXTENSION` (
  `RECORD_ID` VARCHAR(45) NOT NULL,
  `TENANT_ID` VARCHAR(10) NOT NULL,
  `COLUMN_ID` INT NOT NULL,
  `COLUMN_VALUE` VARCHAR(80) NULL,
  PRIMARY KEY (`RECORD_ID`, `TENANT_ID`, `COLUMN_ID`),
  CONSTRAINT `fk_TENANT_RECORD_EXTENSION_TENANT_RECORDS1`
    FOREIGN KEY (`RECORD_ID` , `TENANT_ID`)
    REFERENCES `cmpe281`.`TENANT_RECORDS` (`RECORD_ID` , `TENANT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- TENANT_DATA Record with Extensions Example
insert into TENANT_RECORDS (RECORD_ID, TENANT_ID, TENANT_TABLE ) values ( '1001', 'TA', 'LP_TASK' ) ;
insert into TENANT_RECORD_EXTENSION ( RECORD_ID, TENANT_ID, COLUMN_ID, COLUMN_VALUE ) values ( '1001', 'TA', 1, '1001' ) ;
insert into TENANT_RECORD_EXTENSION ( RECORD_ID, TENANT_ID, COLUMN_ID, COLUMN_VALUE ) values ( '1001', 'TA', 2, 'Design Data Models' ) ;
insert into TENANT_RECORD_EXTENSION ( RECORD_ID, TENANT_ID, COLUMN_ID, COLUMN_VALUE ) values ( '1001', 'TA', 3, 'Paul' ) ;
insert into TENANT_RECORD_EXTENSION ( RECORD_ID, TENANT_ID, COLUMN_ID, COLUMN_VALUE ) values ( '1001', 'TA', 4, '2014-09-01' ) ;
insert into TENANT_RECORD_EXTENSION ( RECORD_ID, TENANT_ID, COLUMN_ID, COLUMN_VALUE ) values ( '1001', 'TA', 5, '2014-10-01') ;
insert into TENANT_RECORD_EXTENSION ( RECORD_ID, TENANT_ID, COLUMN_ID, COLUMN_VALUE ) values ( '1001', 'TA', 6, 'FALSE' ) ;


-- QUERY DATA
select  R.TENANT_TABLE, 
        C1.COLUMN_VALUE ID, C2.COLUMN_VALUE DESCRIPTION, C3.COLUMN_VALUE OWNER,
        C4.COLUMN_VALUE STARTDATE, C5.COLUMN_VALUE ENDDATE, C6.COLUMN_VALUE DONE
from 	TENANT_RECORDS R,
		TENANT_RECORD_EXTENSION C1,
		TENANT_RECORD_EXTENSION C2,
		TENANT_RECORD_EXTENSION C3,
		TENANT_RECORD_EXTENSION C4,
		TENANT_RECORD_EXTENSION C5,
		TENANT_RECORD_EXTENSION C6
where 	R.TENANT_ID = 'TA' 
and	   	R.RECORD_ID = C1.RECORD_ID and R.TENANT_ID = C1.TENANT_ID and C1.COLUMN_ID = 1
and	   	R.RECORD_ID = C2.RECORD_ID and R.TENANT_ID = C2.TENANT_ID and C2.COLUMN_ID = 2
and	   	R.RECORD_ID = C3.RECORD_ID and R.TENANT_ID = C3.TENANT_ID and C3.COLUMN_ID = 3
and	   	R.RECORD_ID = C4.RECORD_ID and R.TENANT_ID = C4.TENANT_ID and C4.COLUMN_ID = 4
and	   	R.RECORD_ID = C5.RECORD_ID and R.TENANT_ID = C5.TENANT_ID and C5.COLUMN_ID = 5
and	   	R.RECORD_ID = C6.RECORD_ID and R.TENANT_ID = C6.TENANT_ID and C6.COLUMN_ID = 6

-- WITH COLUMN HEADER
select  T.TABLE_NAME, 
        C1.FIELD_NAME, C2.FIELD_NAME, C3.FIELD_NAME,
        C4.FIELD_NAME, C5.FIELD_NAME, C6.FIELD_NAME
from 	TENANT_TABLE T,
		TENANT_FIELDS C1,
		TENANT_FIELDS C2,
		TENANT_FIELDS C3,
		TENANT_FIELDS C4,
		TENANT_FIELDS C5,
		TENANT_FIELDS C6
where 	T.TENANT_ID = 'TA' 
and	   	T.TABLE_NAME = C1.TABLE_NAME and T.TENANT_ID = C1.TENANT_ID and C1.FIELD_COLUMN = 1
and	   	T.TABLE_NAME = C2.TABLE_NAME and T.TENANT_ID = C2.TENANT_ID and C2.FIELD_COLUMN = 2
and	   	T.TABLE_NAME = C3.TABLE_NAME and T.TENANT_ID = C3.TENANT_ID and C3.FIELD_COLUMN = 3
and	   	T.TABLE_NAME = C4.TABLE_NAME and T.TENANT_ID = C4.TENANT_ID and C4.FIELD_COLUMN = 4
and	   	T.TABLE_NAME = C5.TABLE_NAME and T.TENANT_ID = C5.TENANT_ID and C5.FIELD_COLUMN = 5
and	   	T.TABLE_NAME = C6.TABLE_NAME and T.TENANT_ID = C6.TENANT_ID and C6.FIELD_COLUMN = 6
UNION
select  R.TENANT_TABLE, 
        C1.COLUMN_VALUE, C2.COLUMN_VALUE, C3.COLUMN_VALUE,
        C4.COLUMN_VALUE, C5.COLUMN_VALUE, C6.COLUMN_VALUE
from 	TENANT_RECORDS R,
		TENANT_RECORD_EXTENSION C1,
		TENANT_RECORD_EXTENSION C2,
		TENANT_RECORD_EXTENSION C3,
		TENANT_RECORD_EXTENSION C4,
		TENANT_RECORD_EXTENSION C5,
		TENANT_RECORD_EXTENSION C6
where 	R.TENANT_ID = 'TA' 
and	   	R.RECORD_ID = C1.RECORD_ID and R.TENANT_ID = C1.TENANT_ID and C1.COLUMN_ID = 1
and	   	R.RECORD_ID = C2.RECORD_ID and R.TENANT_ID = C2.TENANT_ID and C2.COLUMN_ID = 2
and	   	R.RECORD_ID = C3.RECORD_ID and R.TENANT_ID = C3.TENANT_ID and C3.COLUMN_ID = 3
and	   	R.RECORD_ID = C4.RECORD_ID and R.TENANT_ID = C4.TENANT_ID and C4.COLUMN_ID = 4
and	   	R.RECORD_ID = C5.RECORD_ID and R.TENANT_ID = C5.TENANT_ID and C5.COLUMN_ID = 5
and	   	R.RECORD_ID = C6.RECORD_ID and R.TENANT_ID = C6.TENANT_ID and C6.COLUMN_ID = 6




