

up:
	docker-compose up -d
	echo "Traefik Console Up at:  http://localhost:8080"

down:
	docker-compose down

network-ls:
	docker network ls

network-create:
	docker network create webgateway

network-prune:
	docker network prune