
get:
	go get github.com/cloudnativego/go-primer

hello:
	go run src/github.com/cloudnativego/go-primer/hello-cloud.go

basic-functions:
	go run src/github.com/cloudnativego/go-primer/basic-functions.go

go-structs:
	go run src/github.com/cloudnativego/go-primer/go-structs.go

go-interfaces:
	go run src/github.com/cloudnativego/go-primer/go-interfaces.go

go-package-consumer:
	go run src/github.com/cloudnativego/go-primer/go-package-consumer.go

custom-package-consumer:
	go run src/github.com/cloudnativego/go-primer/custom-package-consumer.go

