/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pnguyen' at '11/3/16 8:03 PM' with Gradle 3.1
 *
 * @author pnguyen, @date 11/3/16 8:03 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
