
run:
	dev_appserver.py app.yaml

deploy:
	gcloud app deploy

project:
	gcloud config set project "pnguyen-gumball"

login:
	gcloud auth login

tail:
	gcloud app logs tail -s default

view:
	gcloud app browse

test:
	curl https://pnguyen-gumball.appspot.com/gumball